### ISSUE TITLE
Does the Assistants feature allow streaming?

### ISSUE THREAD

**Issue by GitHubUsername1** [RageAgainstThePixel/com.openai.unity#215] opened 2024-04-06 15:47 UTC
# Feature Request
Streaming https://platform.openai.com/docs/assistants/overview?context=with-streaming

## Is your feature request related to a problem? Please describe.
OpenAI Assistants API now features streaming, is this supported in this client library?

## Describe the solution you'd like
Streaming to be supported because Assistants API is quite slow, apparently it's better with streaming.

## Describe alternatives you've considered
N/A

## Additional context
I have briefly searched the Read.Me and couldn't find any reference to this already being available (apologies if it is!).

**Comment by StephenHodgson** [comment] 2024-04-06 17:18
Duplicate of https://github.com/RageAgainstThePixel/OpenAI-DotNet/issues/267

**Closed by StephenHodgson** 2024-04-06 17:18 UTC
Labels: enhancement
