### ISSUE TITLE
CreateSpeechAsync doesn't work on WebGL builds

### ISSUE THREAD

**Issue by foundway** [RageAgainstThePixel/com.openai.unity#134] opened 2023-11-30 00:14 UTC
# Bug Report

## Overview
openAI.AudioEndpoint.CreateSpeechAsync throw the following error:
```
63fc5e1f-3537-4cd6-b727-3c7cc79dd4f7:10 System.IO.DirectoryNotFoundException: Could not find a part of the path "/tmp/download_cache/Nova-20231130T120608.mp3".
  at System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.Boolean anonymous, System.IO.FileOptions options) [0x00000] in <00000000000000000000000000000000>:0 
--- End of stack trace from previous location where exception was thrown ---
```
Likely due to some limitation of WebGL

## To Reproduce
Call CreateSpeechAsync using something similar to the sample code in README
```csharp
        try
        {
            var request = new SpeechRequest(text, Model.TTS_1, voice: SpeechVoice.Nova);
            Debug.Log("Asking TTS_1...");
            openAI.AudioEndpoint.EnableDebug = true;
            var (clipPath, clip) = await openAI.AudioEndpoint.CreateSpeechAsync(request, lifetimeCancellationTokenSource.Token);
            audioSource.clip = clip;
            audioSource.Play();
        }
        catch (Exception e)
        {
            Debug.LogError(e);
        }
```

## Expected behavior
I should get an audioClip and its path in return as worked in editor and other platforms

## Screenshots
<img width="653" alt="Screenshot 2023-11-29 at 4 14 08 PM" src="https://github.com/RageAgainstThePixel/com.openai.unity/assets/1289089/95c4b396-11ea-47bf-bda6-11bc1789938a">

**Comment by StephenHodgson** [comment] 2023-11-30 00:17
Are you running this in local host?

**Comment by StephenHodgson** [comment] 2023-11-30 00:19
Due to CORS policy of image storage in local WebGL builds you will get the generated image's URL however it will not be downloaded using UnityWebRequest until you run it out of localhost, on a server.

**Comment by foundway** [comment] 2023-11-30 00:45
I am hosting on GitHub Page:
https://foundway.github.io/WhisperWebGL/TTS/

**Comment by StephenHodgson** [comment] 2023-11-30 00:46
Okay, likely related to https://github.com/RageAgainstThePixel/com.utilities.rest/issues/51

**Comment by StephenHodgson** [comment] 2023-11-30 00:50
Duplicate of https://github.com/RageAgainstThePixel/com.openai.unity/issues/130

**Closed by StephenHodgson** 2023-11-30 00:50 UTC
Labels: bug
