### ISSUE TITLE
Change OpenAI-Beta header to assistants=v2

### ISSUE THREAD

**Issue by marcusx2** [RageAgainstThePixel/com.openai.unity#223] opened 2024-04-22 20:36 UTC
# Feature Request

## Is your feature request related to a problem? Please describe.
To use the new OpenAI api, the `OpenAI-Beta` header needs to be set to `assistants=v2`. It's currently `assistants=v1`

## Describe alternatives you've considered
Alternatively make this header in particular editable for the user, but I don't think you want that.

**Comment by StephenHodgson** [comment] 2024-04-22 20:55
Duplicate of https://github.com/RageAgainstThePixel/OpenAI-DotNet/issues/285

**Closed by StephenHodgson** 2024-04-22 20:55 UTC
Labels: enhancement
