### ISSUE TITLE
Threads?

### ISSUE THREAD

**Issue by yosun** [RageAgainstThePixel/com.openai.unity#122] opened 2023-11-11 06:08 UTC
Hi! Are you implementing Threads? https://platform.openai.com/docs/api-reference/threads/createThread

**Comment by StephenHodgson** [comment] 2023-11-11 12:31
yes. Duplicate of https://github.com/RageAgainstThePixel/OpenAI-DotNet/issues/157

**Closed by StephenHodgson** 2023-11-11 12:31 UTC
Labels: enhancement
